# Generated by Django 2.2.1 on 2019-05-12 13:01

from django.db import migrations, models

import loginsys.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=127, unique=True)),
                ('first_name', models.CharField(default=' ', max_length=30)),
                ('last_name', models.CharField(default=' ', max_length=150)),
                ('organization', models.CharField(default=' ', max_length=150)),
                ('rating', models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', loginsys.models.MyUserManager()),
            ],
        ),
    ]
