# Generated by Django 2.2.1 on 2019-05-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='rating_a',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='rating_i',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
