# Generated by Django 2.1.7 on 2019-04-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='topic',
            name='search_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
