# Generated by Django 2.1.7 on 2019-04-05 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20190405_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='search_name',
        ),
    ]
