# Generated by Django 2.2.1 on 2019-05-08 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0005_solutionrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertsToTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=None, to='manager.Topic')),
            ],
            options={
                'verbose_name': 'Связь эксперт-вопрос',
                'verbose_name_plural': 'Связи эксперт-вопрос',
            },
        ),
    ]
