# Generated by Django 2.2.1 on 2019-05-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20190512_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='image',
            field=models.ImageField(default=None, upload_to='static/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SolutionImage',
        ),
    ]
